server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/ticketbooking_db
spring.datasource.username=root
spring.datasource.password=Skishore007@kpriet
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true